# permissions for end users to view availabilityzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: halcyon
    app.kubernetes.io/managed-by: kustomize
  name: availabilityzone-viewer-role
rules:
- apiGroups:
  - halcyonproj.dev
  resources:
  - availabilityzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - halcyonproj.dev
  resources:
  - availabilityzones/status
  verbs:
  - get
