# permissions for end users to edit datacenters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: halcyon
    app.kubernetes.io/managed-by: kustomize
  name: datacenter-editor-role
rules:
- apiGroups:
  - halcyonproj.dev
  resources:
  - datacenters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - halcyonproj.dev
  resources:
  - datacenters/status
  verbs:
  - get
