# permissions for end users to view fabricclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: halcyon
    app.kubernetes.io/managed-by: kustomize
  name: fabricclass-viewer-role
rules:
- apiGroups:
  - halcyonproj.dev
  resources:
  - fabricclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - halcyonproj.dev
  resources:
  - fabricclasses/status
  verbs:
  - get
