# permissions for end users to edit physicalports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: halcyon
    app.kubernetes.io/managed-by: kustomize
  name: physicalport-editor-role
rules:
- apiGroups:
  - halcyonproj.dev
  resources:
  - physicalports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - halcyonproj.dev
  resources:
  - physicalports/status
  verbs:
  - get
