# permissions for end users to view physicalinterfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: halcyon
    app.kubernetes.io/managed-by: kustomize
  name: physicalinterface-viewer-role
rules:
- apiGroups:
  - halcyonproj.dev
  resources:
  - physicalinterfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - halcyonproj.dev
  resources:
  - physicalinterfaces/status
  verbs:
  - get
