apiVersion: halcyonproj.dev/v1alpha1
kind: PhysicalPort
metadata:
  labels:
    app.kubernetes.io/name: halcyon
    app.kubernetes.io/managed-by: kustomize
  name: physicalport-sample
spec:
  # TODO(user): Add fields here
