# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/halcyonproj.dev_regions.yaml
- bases/halcyonproj.dev_availabilityzones.yaml
- bases/halcyonproj.dev_datacenters.yaml
- bases/halcyonproj.dev_racks.yaml
- bases/halcyonproj.dev_racktypes.yaml
- bases/halcyonproj.dev_physicalcomputes.yaml
- bases/halcyonproj.dev_physicalcables.yaml
- bases/halcyonproj.dev_physicalinterfaces.yaml
- bases/halcyonproj.dev_physicalswitches.yaml
- bases/halcyonproj.dev_physicalports.yaml
- bases/halcyonproj.dev_fabricclasses.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_availabilityzones.yaml
- path: patches/webhook_in_availabilityzones.yaml
- path: patches/webhook_in_regions.yaml
- path: patches/webhook_in_availabilityzones.yaml
- path: patches/webhook_in_regions.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_regions.yaml
- path: patches/cainjection_in_availabilityzones.yaml
#- path: patches/cainjection_in_datacenters.yaml
#- path: patches/cainjection_in_racks.yaml
#- path: patches/cainjection_in_racktypes.yaml
#- path: patches/cainjection_in_physicalcomputes.yaml
#- path: patches/cainjection_in_physicalcables.yaml
#- path: patches/cainjection_in_physicalinterfaces.yaml
#- path: patches/cainjection_in_physicalswitches.yaml
#- path: patches/cainjection_in_physicalports.yaml
#- path: patches/cainjection_in_fabricclasses.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

configurations:
- kustomizeconfig.yaml
