---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: racktypes.halcyonproj.dev
spec:
  group: halcyonproj.dev
  names:
    kind: RackType
    listKind: RackTypeList
    plural: racktypes
    singular: racktype
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.manufacturer
      name: Manufacturer
      type: string
    - jsonPath: .spec.model
      name: Model
      type: string
    - jsonPath: .spec.formFactor.enclosure
      name: Enclosure
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RackType is the Schema for the racktypes API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: RackTypeSpec defines the desired state of RackType
            properties:
              formFactor:
                properties:
                  enclosure:
                    enum:
                    - cabinet
                    - frame
                    type: string
                  position:
                    enum:
                    - free-standing
                    - mounted
                    type: string
                  posts:
                    enum:
                    - 2
                    - 4
                    type: integer
                required:
                - enclosure
                - position
                - posts
                type: object
              manufacturer:
                type: string
              model:
                type: string
              units:
                properties:
                  end:
                    type: integer
                  order:
                    enum:
                    - top-down
                    - bottom-up
                    type: string
                  start:
                    type: integer
                required:
                - end
                - order
                - start
                type: object
            required:
            - formFactor
            - manufacturer
            - model
            - units
            type: object
          status:
            description: RackTypeStatus defines the observed state of RackType
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
