name: PRCI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  actions: read
  checks: read
  statuses: read

jobs:
  ensure-ci-success:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure CI Success
        uses: DataDog/ensure-ci-success@b0d931ac77c810490e61964c321103040eef888e
        with:
          full-details-summary: true
